language: java
os: linux
dist: bionic
arch: amd64
jdk:
  - openjdk11
stages:
  - compile
  - test

if: branch = master

jobs:
  include:
    - stage: compile
      script: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage: test
      script: ./mvnw test -B
